[package]
name = "potential-octo-enigma"
version = "0.1.0"
authors = ["Red Carpet <redcarpetoaxaca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18.1"
